### ISSUE TITLE
 How to Install php_mongo module in bitnami Mean stack on windows 7

### ISSUE THREAD

**Issue by cruxster** [iwind/rockmongo#119]
I have Installed Bitnami Mean stack in my windows 7. after installation everything working fine . 

Bitnami welcome page opening but when i opening my mongodb admin page  url: http://localhost/rockmongo/ it shows this statement:

**_To make things right, you must install php_mongo module. Here for installation documents on PHP.net._**

i have followed the installation process  which is available  on PHP.net.

1. I have download php_mongo.dll folder and unzip  plus placed the dll file in bitnami php folder ->ext

2. Plus also  Added extension=php_mongo.dll in php.ini file in php folder of bitnami.

but still i cant see mongodb admin panel.

Please help!!!.

**Comment by davidbhlm-github** [comment]
Hi,

Sorry for the inconvenience. It should be fixed from version 3.2.3-1. 

Regards

**Comment by bhattaxay** [comment]
I also facing the same issue, still the process is simple. The problem is not resolved yet.
